name: flutter_clean_architecture
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^2.24.2
  cloud_firestore: ^4.14.0
  firebase_auth: ^4.16.0
  uuid: ^3.0.7
  fluttertoast: 8.2.2
  intl: ^0.19.0
  contacts_service: ^0.6.3
  flutter_contacts: ^1.1.7+1
  image_picker: 1.0.4
  file_picker: ^5.2.11
  video_player: ^2.8.2

  firebase_storage: ^11.6.0
  flutter_pin_code_fields: ^2.1.0
  country_picker: ^2.0.20
  cached_network_image: ^3.3.1
  #http: ^0.13.5
  country_pickers: ^2.0.0
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  get_it: ^7.6.6
  font_awesome_flutter: 10.5.0
  agora_uikit: ^1.3.1
  get_time_ago: ^1.3.1
  swipe_to: ^1.0.2
  emoji_picker_flutter: ^1.6.3

  giphy_picker: ^3.0.1
  #enough_giphy: ^0.2.0
  #enough_giphy_flutter: ^0.4.0
  flutter_sound: ^9.2.13
  path_provider: ^2.0.14
  audioplayers: 5.1.0
  just_audio: ^0.9.32
  flutter_story_view: 0.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/bg_image.png
    - assets/meta.png
    - assets/profile_default.png
    - assets/whats_app_logo.png
    - assets/whatsapp_bg_image.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
